<?xml version="1.0"?>
<!-- 声明一个xml文档 -->

<!DOCTYPE note [
<!ELEMENT note (to,from,head,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT head (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT 中文 (#PCDATA)>
<!ENTITY to "afei">
<!ENTITY from "xiaohe">
<!ENTITY 中文 "你好阿飞">
]>

<note>
	<to>afei</to>
    <from>xiaohe</from>
    <head>message</head>
    <body>nnsshxs</body>
    <中文>中文测试</中文>
    <to>&to;</to>
    <from>&from;</from>

</note>

<!DOCTYPE name [
<!ELEMENT name (na)
<!ELEMENT na>
<!ENTITY na SYSTEM "file:///c:/test.txt">
]>
<na>&na;</na>